### PR TITLE
Set the logger in the base logger [HZG-188]

### LINKED ISSUE #1235: C++ client incompatible with Hazelcast`5.5.0` [HZG-188]
[When testing C++ client against Hazelcast `5.5.0`, the PR builder failed with](https://github.com/hazelcast/hazelcast-cpp-client/actions/runs/10507370808):
```
2025-03-20T14:57:05.6591790Z INFO: [localhost]:5701 [dev] [5.5.0] [localhost]:5701 is STARTED
2025-03-20T14:57:05.6600940Z 14:57:05,659  INFO [Main] - Ping ... Pong ...
2025-03-20T14:57:05.6623500Z 20/03/2025 14:57:05.661 INFO: [0x16b44b000] hz.client_1[dev] [5.3] (Thu Mar 20 14:48:56 2025 +0000:33897ea) LifecycleService::LifecycleEvent Client (b0fdfbb9-639c-4a21-805f-30a57d39cd89) is STARTING
2025-03-20T14:57:05.6628900Z 20/03/2025 14:57:05.661 INFO: [0x16b44b000] hz.client_1[dev] [5.3] (Thu Mar 20 14:48:56 2025 +0000:33897ea) LifecycleService::LifecycleEvent STARTING
2025-03-20T14:57:05.6631030Z 20/03/2025 14:57:05.661 INFO: [0x16b44b000] hz.client_1[dev] [5.3] LifecycleService::LifecycleEvent STARTED
2025-03-20T14:57:05.6642750Z 20/03/2025 14:57:05.662 INFO: [0x16b44b000] hz.client_1[dev] [5.3] Trying to connect to Address[127.0.0.1:5701].
2025-03-20T14:57:05.6869660Z Mar 20, 2025 2:57:05 PM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
2025-03-20T14:57:05.6871470Z INFO: [localhost]:5701 [dev] [5.5.0] Received auth from Connection[id=1, /127.0.0.1:5701->/127.0.0.1:49224, qualifier=null, endpoint=[127.0.0.1]:49224, remoteUuid=b0fdfbb9-639c-4a21-805f-30a57d39cd89, alive=true, connectionType=CPP, planeIndex=-1], successfully authenticated, clientUuid: b0fdfbb9-639c-4a21-805f-30a57d39cd89, client name: hz.client_1, client version: 5.3
2025-03-20T14:57:05.6973600Z 20/03/2025 14:57:05.697 INFO: [0x16b44b000] hz.client_1[dev] [5.3] LifecycleService::LifecycleEvent CLIENT_CONNECTED
2025-03-20T14:57:05.6978690Z 20/03/2025 14:57:05.697 INFO: [0x16b44b000] hz.client_1[dev] [5.3] Authenticated with server  Address[localhost:5701]:564429cc-b05d-4bf8-988f-04179cb22586, server version: 5.5.0, local address: Address[127.0.0.1:49224]. Connection{alive=1, connection id=1, remote endpoint=Address[localhost:5701], last_read_time=2025-03-20 14:57:05.695, last_write_time=2025-03-20 14:57:05.664, closedTime=never, connected server version=5.5.0}
2025-03-20T14:57:05.7071720Z 20/03/2025 14:57:05.706 WARNING: [0x16c053000] hz.client_1[dev] [5.3] No invocation for callId:  0. Dropping this message: ClientMessage{length=61, operation=, isRetryable=0, correlationId = 0, messageType = 0x304, flags = 0xc200, is backup aware = 0, is backup event = 0, isEvent = 1}, is_fragmented = no
2025-03-20T14:57:05.7073140Z 20/03/2025 14:57:05.706 INFO: [0x16bd0b000] hz.client_1[dev] [5.3] 
2025-03-20T14:57:05.7076280Z 
2025-03-20T14:57:05.7076570Z Members [1]  {
2025-03-20T14:57:05.7077090Z 	Member[localhost]:5701 - 564429cc-b05d-4bf8-988f-04179cb22586
2025-03-20T14:57:05.7181200Z ./scripts/test-unix.sh: line 60: 27824 Segmentation fault: 11  ${TEST_EXECUTABLE} --gtest_output="xml:CPP_Client_Test_Report.xml"
2025-03-20T14:57:05.7182730Z }
2025-03-20T14:57:05.7195620Z 
2025-03-20T14:57:05.7201530Z Mar 20, 2025 2:57:05 PM com.hazelcast.internal.server.tcp.TcpServerConnection
2025-03-20T14:57:05.7204640Z Test FAILED. Result:139
```

### PR DESCRIPTION
**Pull request by ihsandemir**
Updated the test server version. Fixed the null logger problem. The event handler logger was not set properly.

Associated protocol PR is [here](https://github.com/hazelcast/hazelcast-client-protocol/pull/549)

fixes #1235
closes: https://github.com/hazelcast/hazelcast-cpp-client/pull/1270

### CODE REVIEW

File: hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.h [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
+ * Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
```
Comment (JackPGreen) [inline hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.h:2]: Bit confused by this change?

Comment (ihsandemir) [reply hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.h]: let me revert. I had to go back to an earlier commit to re-generated the codecs with the change for base handler and that version somehow had earlier year. 
fixed at dadf0a37fafe491ff64e2de6c17018f80287caba

File: scripts/start-rc.sh [hunk 2]
```diff
@@ -34,7 +34,7 @@ set +x
 
 trap cleanup EXIT
 
-HZ_VERSION=${HZ_VERSION:-5.4.0}
+HZ_VERSION=${HZ_VERSION:-5.5.0}
```
Comment (JackPGreen) [inline scripts/start-rc.sh:37]: We should also adjust config.env - it’s what’s actually used for CI.

https://github.com/ihsandemir/hazelcast-cpp-client/blob/dadf0a37fafe491ff64e2de6c17018f80287caba/.github/config.env#L4

**Comment by JackPGreen** [comment]
> Fixed the null logger problem.

To be clear - the segmentation fault we saw was dereferencing a null `logger` pointer. The client PR sets the architure in place to ensure a `logger` _reference_ is present, and this PR just plugs one in where necessary to satisfy that.

<sup>_(this is just me making sure I understand!)_<sup>

How did you figure this out? Could we extend the [`DEBUG` PR build](https://github.com/hazelcast/hazelcast-cpp-client/actions/runs/15032113668/job/42246730374) to resolve a stack trace if this happens again?

I've tried adding [`asan`](https://learn.microsoft.com/en-us/cpp/sanitizers/asan) and [doing a test build](https://github.com/hazelcast/hazelcast-cpp-client/actions/runs/15032576422) and that _seems_ to have provided information that _might_ have helped:
https://github.com/hazelcast/hazelcast-cpp-client/blob/b08f998498dc799822dccc0840bb1ff7fad92f19/.github/actions/build-test/unix/action.yml#L57

```
=================================================================
==37978==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000040 (pc 0x7eff21446d48 bp 0x7efeff67fce0 sp 0x7efeff67fcd0 T22)
==37978==The signal is caused by a READ memory access.
==37978==Hint: address points to the zero page.

    #0 0x7eff21446d48 in hazelcast::logger::enabled(hazelcast::logger::level) /home/runner/work/hazelcast-cpp-client/hazelcast-cpp-client/hazelcast/src/hazelcast/logger.cpp:71
    #1 0x7eff20a05b1d in hazelcast::client::protocol::codec::client_addclusterviewlistener_handler::handle(hazelcast::client::protocol::ClientMessage&) /home/runner/work/hazelcast-cpp-client/hazelcast-cpp-client/hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.cpp:145

{...}

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/runner/work/hazelcast-cpp-client/hazelcast-cpp-client/hazelcast/src/hazelcast/logger.cpp:71 in hazelcast::logger::enabled(hazelcast::logger::level)
```

File: scripts/start-rc.sh (hunk 2 above)
Comment (ihsandemir) [reply scripts/start-rc.sh]: fixed at 665f51b538b3bf4f74940f98d64e77aeae55dc29

**Comment by ihsandemir** [comment]
> > Fixed the null logger problem.
> 
> To be clear - the segmentation fault we saw was dereferencing a null `logger` pointer. The client PR sets the architure in place to ensure a `logger` _reference_ is present, and this PR just plugs one in where necessary to satisfy that.
> 
> _(this is just me making sure I understand!)_
> 
> How did you figure this out? Could we extend the [`DEBUG` PR build](https://github.com/hazelcast/hazelcast-cpp-client/actions/runs/15032113668/job/42246730374) to resolve a stack trace if this happens again?
> 
> I've tried adding [`asan`](https://learn.microsoft.com/en-us/cpp/sanitizers/asan) and [doing a test build](https://github.com/hazelcast/hazelcast-cpp-client/actions/runs/15032576422) and that _seems_ to have provided information that _might_ have helped:
> 
> https://github.com/hazelcast/hazelcast-cpp-client/blob/b08f998498dc799822dccc0840bb1ff7fad92f19/.github/actions/build-test/unix/action.yml#L57
> 
> ```
> =================================================================
> ==37978==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000040 (pc 0x7eff21446d48 bp 0x7efeff67fce0 sp 0x7efeff67fcd0 T22)
> ==37978==The signal is caused by a READ memory access.
> ==37978==Hint: address points to the zero page.
> 
>     #0 0x7eff21446d48 in hazelcast::logger::enabled(hazelcast::logger::level) /home/runner/work/hazelcast-cpp-client/hazelcast-cpp-client/hazelcast/src/hazelcast/logger.cpp:71
>     #1 0x7eff20a05b1d in hazelcast::client::protocol::codec::client_addclusterviewlistener_handler::handle(hazelcast::client::protocol::ClientMessage&) /home/runner/work/hazelcast-cpp-client/hazelcast-cpp-client/hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.cpp:145
> 
> {...}
> 
> AddressSanitizer can not provide additional info.
> SUMMARY: AddressSanitizer: SEGV /home/runner/work/hazelcast-cpp-client/hazelcast-cpp-client/hazelcast/src/hazelcast/logger.cpp:71 in hazelcast::logger::enabled(hazelcast::logger::level)
> ```

Would you like to to put it into the `build_unix.sh` and `build-windows.bat` so that we do not override those values and also that is where we put these flags common for all runs, but should we put it for debug builds only?

File: .github/config.env [hunk 3]
```diff
@@ -1,4 +1,4 @@
 JAVA_VERSION=17
 JAVA_DISTRIBUTION=temurin
 MAVEN_VERSION=3.9.9
-HZ_VERSION=5.4.0
+HZ_VERSION=5.5.5
```
Comment (JackPGreen) [inline .github/config.env:4]: This is an enterprise-only release - is that right?

**Comment by JackPGreen** [comment]
> Would you like to to put it into the `build_unix.sh` and `build-windows.bat` so that we do not override those values and also that is where we put these flags common for all runs, but should we put it for debug builds only?

I can raise a separate PR to improve debug failure messages, just wanted to check I was on the right track.

**Comment by ihsandemir** [comment]
> > Would you like to to put it into the `build_unix.sh` and `build-windows.bat` so that we do not override those values and also that is where we put these flags common for all runs, but should we put it for debug builds only?
> 
> I can raise a separate PR to improve debug failure messages, just wanted to check I was on the right track.

Definitely on the right track. Go ahead and submit a PR, I will review it. For release builds, we want optimized binary without any debug overheads since the users also build similar to us from source code, hence, asan would be useful for debug builds and make sure it works for all os types we support in the ci builds.

File: .github/config.env (hunk 3 above)
Comment (ihsandemir) [reply .github/config.env:4]: yes.

**Review by emreyigit — APPROVED** [review]

File: .github/config.env (hunk 3 above)
Comment (JackPGreen) [reply .github/config.env:4]: > yes.

It doesn't look like it'll work to me.

https://github.com/hazelcast/hazelcast-cpp-client/blob/b501d578af5c6d0b7af2753cce0d7b9776fc99d9/scripts/start-rc.bat#L7

https://github.com/hazelcast/hazelcast-cpp-client/blob/b501d578af5c6d0b7af2753cce0d7b9776fc99d9/scripts/start-rc.bat#L10

https://github.com/hazelcast/hazelcast-cpp-client/blob/b501d578af5c6d0b7af2753cce0d7b9776fc99d9/scripts/start-rc.bat#L35-L43

based on ^ that ^ I think it'll try to download the `-tests` & `hazelcast-sql` `5.5.5` JARs from the central snapshot repo (where the EE ones aren't) and it'll fail.

What's wrong with using the released `5.5.0` version?

Comment (ihsandemir) [reply .github/config.env:4]: fixed the download repo problem. no, i just wanted to use latest patched release to test against since that is what we recommend to the customers. nothing special.

**Review by JackPGreen — APPROVED** [review]
