### PR TITLE
Fix error in get_all imap method with hazelcast_json_value value type

### LINKED ISSUE #925: Error in get_all imap method with hazelcast_json_value value type
C++ compiler version: gcc 10.3.0
Hazelcast Cpp client version: 4.2.0
Hazelcast server version: -
Number of the clients: 1
Cluster size, i.e. the number of Hazelcast cluster members: -
OS version (Windows/Linux/OSX): Linux Ubuntu 21.04

#### Expected behaviour
`get_all<std::string, hazelcast_json_value>` compiles successfully and produce correct output(`unordered_map<std::string, hazelcast_json_value>` with entries with keys from `unordered_set<string>` type parameter)

#### Actual behaviour
```
In file included from /usr/include/c++/10/ranges:46,
                 from /usr/include/c++/10/bits/ranges_algobase.h:38,
                 from /usr/include/c++/10/bits/ranges_algo.h:35,
                 from /usr/include/c++/10/algorithm:64,
                 from /home/rikevoltz/.conan/data/boost/1.76.0/_/_/package/8468b057bf5b2cf5c1e9194777c025a4812bc62f/include/boost/utility/string_view.hpp:30,
                 from /home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/hazelcast_client.h:18,
                 from /data/work/test-tasks/untitled5/main.cpp:1:
/usr/include/c++/10/tuple: In instantiation of ‘constexpr std::pair<_T1, _T2>::pair(std::tuple<_Args1 ...>&, std::tuple<_Args2 ...>&, std::_Index_tuple<_Indexes1 ...>, std::_Index_tuple<_Indexes2 ...>) [with _Args1 = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&}; long unsigned int ..._Indexes1 = {0}; _Args2 = {}; long unsigned int ..._Indexes2 = {}; _T1 = const std::__cxx11::basic_string<char>; _T2 = hazelcast::client::hazelcast_json_value]’:
/usr/include/c++/10/tuple:1682:63:   required from ‘constexpr std::pair<_T1, _T2>::pair(std::piecewise_construct_t, std::tuple<_Args1 ...>, std::tuple<_Args2 ...>) [with _Args1 = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&}; _Args2 = {}; _T1 = const std::__cxx11::basic_string<char>; _T2 = hazelcast::client::hazelcast_json_value]’
/usr/include/c++/10/bits/stl_construct.h:97:14:   required from ‘constexpr decltype (::new(void*(0)) _Tp) std::construct_at(_Tp*, _Args&& ...) [with _Tp = std::pair<const std::__cxx11::basic_string<char>, hazelcast::client::hazelcast_json_value>; _Args = {const std::piecewise_construct_t&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&>, std::tuple<>}; decltype (::new(void*(0)) _Tp) = std::pair<const std::__cxx11::basic_string<char>, hazelcast::client::hazelcast_json_value>*]’
/usr/include/c++/10/bits/alloc_traits.h:514:4:   required from ‘static constexpr void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = std::pair<const std::__cxx11::basic_string<char>, hazelcast::client::hazelcast_json_value>; _Args = {const std::piecewise_construct_t&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&>, std::tuple<>}; _Tp = std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, hazelcast::client::hazelcast_json_value>, true>; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, hazelcast::client::hazelcast_json_value>, true> >]’
/usr/include/c++/10/bits/hashtable_policy.h:2037:36:   required from ‘std::__detail::_Hashtable_alloc<_NodeAlloc>::__node_type* std::__detail::_Hashtable_alloc<_NodeAlloc>::_M_allocate_node(_Args&& ...) [with _Args = {const std::piecewise_construct_t&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&>, std::tuple<>}; _NodeAlloc = std::allocator<std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, hazelcast::client::hazelcast_json_value>, true> >; std::__detail::_Hashtable_alloc<_NodeAlloc>::__node_type = std::allocator<std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, hazelcast::client::hazelcast_json_value>, true> >::value_type]’
/usr/include/c++/10/bits/hashtable.h:272:35:   required from ‘std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_Scoped_node::_Scoped_node(std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__hashtable_alloc*, _Args&& ...) [with _Args = {const std::piecewise_construct_t&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&>, std::tuple<>}; _Key = std::__cxx11::basic_string<char>; _Value = std::pair<const std::__cxx11::basic_string<char>, hazelcast::client::hazelcast_json_value>; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, hazelcast::client::hazelcast_json_value> >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<std::__cxx11::basic_string<char> >; _H1 = std::hash<std::__cxx11::basic_string<char> >; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__hashtable_alloc = std::_Hashtable<std::__cxx11::basic_string<char>, std::pair<const std::__cxx11::basic_string<char>, hazelcast::client::hazelcast_json_value>, std::allocator<std::pair<const std::__cxx11::basic_string<char>, hazelcast::client::hazelcast_json_value> >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char> >, std::hash<std::__cxx11::basic_string<char> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::__hashtable_alloc]’
/usr/include/c++/10/bits/hashtable_policy.h:739:42:   required from ‘std::__detail::_Map_base<_Key, _Pair, _Alloc, std::__detail::_Select1st, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits, true>::mapped_type& std::__detail::_Map_base<_Key, _Pair, _Alloc, std::__detail::_Select1st, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits, true>::operator[](std::__detail::_Map_base<_Key, _Pair, _Alloc, std::__detail::_Select1st, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits, true>::key_type&&) [with _Key = std::__cxx11::basic_string<char>; _Pair = std::pair<const std::__cxx11::basic_string<char>, hazelcast::client::hazelcast_json_value>; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, hazelcast::client::hazelcast_json_value> >; _Equal = std::equal_to<std::__cxx11::basic_string<char> >; _H1 = std::hash<std::__cxx11::basic_string<char> >; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>; std::__detail::_Map_base<_Key, _Pair, _Alloc, std::__detail::_Select1st, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits, true>::mapped_type = hazelcast::client::hazelcast_json_value; std::__detail::_Map_base<_Key, _Pair, _Alloc, std::__detail::_Select1st, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits, true>::key_type = std::__cxx11::basic_string<char>]’
/usr/include/c++/10/bits/unordered_map.h:988:20:   required from ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::mapped_type& std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::operator[](std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_type&&) [with _Key = std::__cxx11::basic_string<char>; _Tp = hazelcast::client::hazelcast_json_value; _Hash = std::hash<std::__cxx11::basic_string<char> >; _Pred = std::equal_to<std::__cxx11::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, hazelcast::client::hazelcast_json_value> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::mapped_type = hazelcast::client::hazelcast_json_value; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_type = std::__cxx11::basic_string<char>]’
/home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/imap.h:606:95:   required from ‘boost::future<std::unordered_map<K, V> > hazelcast::client::imap::get_all(const std::unordered_set<K>&) [with K = std::__cxx11::basic_string<char>; V = hazelcast::client::hazelcast_json_value]’
/data/work/test-tasks/untitled5/main.cpp:12:100:   required from here
/usr/include/c++/10/tuple:1693:70: error: no matching function for call to ‘hazelcast::client::hazelcast_json_value::hazelcast_json_value()’
 1693 |         second(std::forward<_Args2>(std::get<_Indexes2>(__tuple2))...)
      |                                                                      ^
In file included from /home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/serialization/serialization.h:27,
                 from /home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/address.h:20,
                 from /home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/member.h:22,
                 from /home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/entry_event.h:20,
                 from /home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/proxy/IMapImpl.h:18,
                 from /home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/imap.h:31,
                 from /home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/map/NearCachedClientMapProxy.h:20,
                 from /home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/impl/hazelcast_client_instance_impl.h:25,
                 from /home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/hazelcast_client.h:20,
                 from /data/work/test-tasks/untitled5/main.cpp:1:
/home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/hazelcast_json_value.h:57:13: note: candidate: ‘hazelcast::client::hazelcast_json_value::hazelcast_json_value(std::string)’
   57 |             hazelcast_json_value(std::string json_string);
      |             ^~~~~~~~~~~~~~~~~~~~
/home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/hazelcast_json_value.h:57:13: note:   candidate expects 1 argument, 0 provided
/home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/hazelcast_json_value.h:47:29: note: candidate: ‘hazelcast::client::hazelcast_json_value::hazelcast_json_value(const hazelcast::client::hazelcast_json_value&)’
   47 |         class HAZELCAST_API hazelcast_json_value {
      |                             ^~~~~~~~~~~~~~~~~~~~
/home/rikevoltz/.conan/data/hazelcast-cpp-client/4.2.0/_/_/package/b6cff00c6e889ed4b4f34b8276cb295ad1bb45c3/include/hazelcast/client/hazelcast_json_value.h:47:29: note:   candidate expects 1 argument, 0 provided
```

#### Steps to reproduce the behaviour
```cpp
#include <hazelcast/client/hazelcast_client.h>
#include <hazelcast/client/hazelcast_json_value.h>

using json = hazelcast::client::hazelcast_json_value;

int main() {
  auto client = hazelcast::new_client().get();
  auto some_map = client.get_map("test_map").get();
  some_map->put("some_key", json(R"({"id":"some_id"})")).get();
  some_map->put("some_other_key", json(R"({"id":"some_other_id"})")).get();
  some_map->put("another_key", json(R"({"id":"another_id"})")).get();
  auto results = some_map->get_all<std::string, json>({"some_key", "some_other_key", "another_key"}).get();
  return 0;
}
```

### PR DESCRIPTION
**Pull request by RikeVoltz**
This PR closes #925

### CODE REVIEW

**Comment by RikeVoltz** [comment]
Hello there :)
image

**Comment by ihsandemir** [comment]
run-lab-run

**Comment by ihsandemir** [comment]
Thanks for the PR.

**Review by ihsandemir — DISMISSED** [review]

**Comment by yemreinci** [comment]
verify

File: hazelcast/include/hazelcast/client/imap.h [hunk 1]
```diff
@@ -603,9 +603,8 @@ namespace hazelcast {
                                                                                                 entry.second);
                                                                                         // it is guaranteed that all values are non-null
                                                                                         assert(val.has_value());
-                                                                                        result[to_object<K>(
-                                                                                                entry.first).value()] = std::move(
-                                                                                                val.value());
+                                                                                        result.emplace(to_object<K>(
+                                                                                                entry.first).value(), val.value());
```
Comment (yemreinci) [inline hazelcast/include/hazelcast/client/imap.h:607]: This change will introduce an additional copy of the value, right? Can't we still move the value, so the move ctor is called instead of the copy ctor?
```suggestion
                                                                                        result.emplace(to_object<K>(
                                                                                                entry.first).value(), std::move(val.value()));
```

Comment (RikeVoltz) [reply hazelcast/include/hazelcast/client/imap.h]: Yes, you're absolutely right, thank you for the suggestion!

**Comment by yemreinci** [comment]
verify

File: hazelcast/include/hazelcast/client/imap.h (hunk 1 above)
Comment (yemreinci) [reply hazelcast/include/hazelcast/client/imap.h]: Thanks!

**Review by yemreinci — APPROVED** [review]

**Review by ihsandemir — APPROVED** [review]
