### PR TITLE
local_date parse bug is fixed. Tests are added.

### LINKED ISSUE #1125: Wrong SQL TIMESTAMP column value [API-1914]
@OzanCansel 's Using ```inline std::ostream& operator<<(std::ostream& os, const hazelcast::client::local_date_time& dt)
{
    return os << int(dt.date.year)
              << "-"
              << int(dt.date.month)
              << "-"
              << int(dt.date.day_of_month)
              << "T"
              << int(dt.time.hours)
              << ":"
              << int(dt.time.minutes)
              << ":"
              << int(dt.time.seconds)
			  ;
}```

prints 
```
231-2-28T13:19:41
```
CCYY is wrong, should be 2023.

Sql column value is read wrong.

### PR DESCRIPTION
**Pull request by OzanCansel**
`local_date` is parsed wrongly in `ClientMessage` it is fixed.

Relevant tests are added to `sql_test.cpp` as well.

Closes #1125

### CODE REVIEW

File: hazelcast/test/src/ClientTest.h [hunk 1]
```diff
@@ -88,6 +91,50 @@ class ClientTest : public ::testing::Test
...
+      const std::string& map_name,
+      const std::string& cluster_id,
+      int n_entries = 10,
+      ValueGenerator&& value_gen = ValueGenerator{},
+      KeyGenerator&& key_gen = KeyGenerator{})
+    {
+        std::unordered_map<Key, Value> entries;
+        entries.reserve(n_entries);
+
+        generate_n(
```
Comment (akeles85) [inline hazelcast/test/src/ClientTest.h:109]: std namespace can be used before generate_n and inserter methods.

**Review by akeles85 — APPROVED** [review]

File: hazelcast/test/src/ClientTest.h (hunk 1 above)
Comment (OzanCansel) [reply hazelcast/test/src/ClientTest.h:109]: I intentionally don't use those qualifiers, if they are unnecessary

**Review by akeles85 — APPROVED** [review]
