### PR TITLE
Compact test failures

### LINKED ISSUE #1090: Compact Test Case Failures in Github Actions [API-1871]
C++ compiler version: clang 14
Hazelcast Cpp client version: 5.1.0
Hazelcast server version: 5.1.3
Number of the clients:
Cluster size, i.e. the number of Hazelcast cluster members:
OS version (Windows/Linux/OSX): All

Please attach relevant logs and files for client and server side.

#### Expected behaviour
Pass test

#### Actual behaviour
Failed tests

#### Steps to reproduce the behaviour
Here is the [link](https://github.com/hazelcast/hazelcast-cpp-client/actions/runs/4119357506/jobs/7112925109).
[compact_failed_test.txt](https://github.com/hazelcast/hazelcast-cpp-client/files/10685192/compact_failed_test.txt)

### PR DESCRIPTION
**Pull request by akeles85**
Fixes #1090 
As I observed, the problem occurs in static library. It does not occur in dynamic library.
The problem is occured because of the static member initialization order. As there are template schemas, the build_schema function is called at startup. As finger print table is also initialized at startup, the schemas are built with empty table.

### CODE REVIEW

File: hazelcast/src/hazelcast/client/compact.cpp [hunk 1]
```diff
@@ -1489,6 +1489,8 @@ field_descriptor::field_descriptor(enum field_kind f,
 std::array<uint64_t, 256>
 init_fp_table()
 {
+    std::mutex tmp_mutex;
+    std::lock_guard<std::mutex> lg(tmp_mutex);
```
Comment (OzanCansel) [inline hazelcast/src/hazelcast/client/compact.cpp:1493]: Lock is not required, static initialization is already thread safe,

```suggestion
```

**Review by OzanCansel — CHANGES_REQUESTED** [review]

File: hazelcast/src/hazelcast/client/compact.cpp (hunk 1 above)
Comment (akeles85) [reply hazelcast/src/hazelcast/client/compact.cpp:1493]: I put it because of the static FP_TABLE initialization in init_fp_table. But maybe it will be better to remove both mutex and static keyword in this function.

**Review by OzanCansel — APPROVED** [review]

File: hazelcast/src/hazelcast/client/compact.cpp [hunk 2]
```diff
@@ -1500,12 +1500,12 @@ init_fp_table()
     return FP_TABLE;
 }
 
-static std::array<uint64_t, 256> FP_TABLE = init_fp_table();
 constexpr uint64_t rabin_finger_print::INIT;
 
 uint64_t
 rabin_finger_print::fingerprint64(uint64_t fp, byte b)
 {
+    static std::array<uint64_t, 256> FP_TABLE = init_fp_table();
```
Comment (ihsandemir) [inline hazelcast/src/hazelcast/client/compact.cpp:1508]: will it create a table for each call?

Comment (akeles85) [reply hazelcast/src/hazelcast/client/compact.cpp:1508]: It should be called just once as it is a static variable. So one table is created.

**Review by ihsandemir — APPROVED** [review]
